name: robocorp-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.1.2
  - pip:
    - robocorp==1.0.0
    - robocorp-tasks==2.2.0
    - numpy==1.24.3
    - pandas==1.5.3
    - transformers==4.30.2
    - torch==2.0.1
    - nltk==3.8.1
    - SQLAlchemy==2.0.19
    - matplotlib==3.7.2
    - scikit-learn==1.3.0
    - python-dotenv==1.0.0
    - imaplib2==3.6
    - psycopg2-binary==2.9.6 